/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmBuscaOrdemServico.java
 *
 * Created on 25/02/2012, 16:13:31
 */

package br.com.syscontrol.formularios;

import br.com.syscontrol.controller.OrdemServicoAction;
import br.com.syscontrol.model.OrdemServicoPadrao;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Diego
 */
public class FrmBuscaOrdemServico extends javax.swing.JFrame {

    private ArrayList lista = null;
    private OrdemServicoAction ordemServicoAction;
    private OrdemServicoPadrao ordemServico = null;
    private FrmPrincipal frmPrincipal;


    /** Creates new form FrmBuscaOrdemServico */
    public FrmBuscaOrdemServico() {
        initComponents();
    }

     public FrmBuscaOrdemServico(List lista, FrmPrincipal frmPrincipal,OrdemServicoPadrao ordemServico) {
        initComponents();
        this.lista = (ArrayList) lista;        
        this.frmPrincipal = frmPrincipal;
        ordemServicoAction = this.frmPrincipal.getOrdemServicoAction();
        this.ordemServico = ordemServico;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaOrdens = new javax.swing.JTable();
        btnSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                carregaTelaBuscaOrdemServico(evt);
            }
        });

        tabelaOrdens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaOrdens);

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                    .addComponent(btnSelecionar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregaTelaBuscaOrdemServico(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_carregaTelaBuscaOrdemServico
        // TODO add your handling code here:
        //Monta o grid contendo os dados do usuario
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.LEFT);


        try {
            //Monta tabela de usuarios no grid
            this.getOrdemServicoAction().popularListaOrdensBusca(lista);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao processar busca - Entre em contato com o Administrador do Sistema!. O erro ocorrido foi: " + ex.getMessage(), "Atenção - Aviso", 0);
        }

        tabelaOrdens.setModel( this.getOrdemServicoAction().getBuscaOrdemServicoTableModel());
        tabelaOrdens.getColumnModel().getColumn(0).setCellRenderer(renderer);
        tabelaOrdens.getColumnModel().getColumn(1).setCellRenderer(renderer);
        tabelaOrdens.getColumnModel().getColumn(2).setCellRenderer(renderer);
        tabelaOrdens.getColumnModel().getColumn(3).setCellRenderer(renderer);
        tabelaOrdens.getColumnModel().getColumn(4).setCellRenderer(renderer);
        tabelaOrdens.getColumnModel().getColumn(0).setMaxWidth(95);
        tabelaOrdens.getColumnModel().getColumn(1).setMaxWidth(100);
        tabelaOrdens.getColumnModel().getColumn(2).setMaxWidth(230);
        tabelaOrdens.getColumnModel().getColumn(3).setMaxWidth(90);
        tabelaOrdens.getColumnModel().getColumn(4).setMaxWidth(80);
    }//GEN-LAST:event_carregaTelaBuscaOrdemServico

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
         try {
                //Ordem Selecionada
                int linhaSelecionada = tabelaOrdens.getSelectedRow();
                this.ordemServico = this.getOrdemServicoAction().getBuscaOrdemServicoTableModel().getLinhas().get(linhaSelecionada);
                this.ordemServico = (OrdemServicoPadrao) this.getOrdemServicoAction().getOsPorId(ordemServico.getIdOrdemServico());
                this.getOrdemServicoAction().notifyObservers(ordemServico);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(FrmBuscaPedido.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBuscaOrdemServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaOrdens;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ordemServicoAction
     */
    public OrdemServicoAction getOrdemServicoAction() {
        return ordemServicoAction;
    }

    /**
     * @param ordemServicoAction the ordemServicoAction to set
     */
    public void setOrdemServicoAction(OrdemServicoAction ordemServicoAction) {
        this.ordemServicoAction = ordemServicoAction;
    }

    /**
     * @return the ordemServico
     */
    public OrdemServicoPadrao getOrdemServico() {
        return ordemServico;
    }

    /**
     * @param ordemServico the ordemServico to set
     */
    public void setOrdemServico(OrdemServicoPadrao ordemServico) {
        this.ordemServico = ordemServico;
    }

}
