/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmGerenciaServicosContrato.java
 *
 * Created on 18/12/2011, 17:30:43
 */

package br.com.syscontrol.formularios;



import br.com.syscontrol.controller.GenericAction;
import br.com.syscontrol.controller.OrdemServicoAction;
import br.com.syscontrol.controller.ServicoAction;
import br.com.syscontrol.helper.Util;
import br.com.syscontrol.model.ItemPedido;
import br.com.syscontrol.model.Servico;
import br.com.syscontrol.model.ServicoDisponivelTableModel;
import br.com.syscontrol.model.ServicoPedidoTableModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Diego
 */
public class FrmGerenciaServicosOS extends JFrame{

      
    private SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");    
    private OrdemServicoAction ordemServicoAction;
    private ServicoAction servicoAction = new ServicoAction();
    private List itensOriginais = new ArrayList();
    private JTable tabelaServicosOS;
    private JTextField txtTotalTelaOS;
    private JTable tabelaServicosOSOriginal;
    private Double valorTotalOriginal;
    private FrmPrincipal frmPrincipal;
    

    /** Creates new form FrmGerenciaServicosContrato */
    public FrmGerenciaServicosOS() {
        initComponents();
    }

    /*
     * @Param ga = OrdemServicoAction
     * @Param tabelaServicosOS = Tabela de serviços da tab de OS no frame principal
     * @Param txtTotal = Campo de total da OS no frame principal
     */
    public FrmGerenciaServicosOS(FrmPrincipal frmPrincipal,GenericAction ga,JTable t,JTextField txtTotal) {
        initComponents();
        
        this.ordemServicoAction = (OrdemServicoAction) ga;
        this.tabelaServicosOS = t;
        tabelaServicosOSOriginal = t;
        txtTotalTelaOS = txtTotal;
        this.frmPrincipal = frmPrincipal;
        try {
            valorTotalOriginal = new Util().converteValorTextoDouble(txtTotalTelaOS.getText());
        } catch (ParseException ex) {
            Logger.getLogger(FrmGerenciaServicosOS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void salvarItensOriginais(JTable tabelaServicosOS){

        List l = ((ServicoPedidoTableModel)tabelaServicosOS.getModel()).getLinhas();
        Iterator i = l.iterator();
        ItemPedido ip;

        while(i.hasNext()){
            ip = (ItemPedido) i.next();
            this.itensOriginais.add(ip);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableServicosDisponiveis = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        adicionaItem = new javax.swing.JButton();
        removeItem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaServicosOSGerenciador = new javax.swing.JTable();
        txtTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        gravaItensOS = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                fecharJanela(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                carregarTelaServicoContrato(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Serviços Disponíveis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        tableServicosDisponiveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableServicosDisponiveis);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel1.setText("% Desconto");

        txtDesconto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtDesconto.setText("10");
        txtDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                validaDesconto(evt);
            }
        });

        adicionaItem.setText("adicionar");
        adicionaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionaItemActionPerformed(evt);
            }
        });

        removeItem.setText("remover");
        removeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Serviços Aplicados a OS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        tabelaServicosOSGerenciador.setBackground(new java.awt.Color(153, 255, 153));
        tabelaServicosOSGerenciador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaServicosOSGerenciador);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtTotal.setFont(new java.awt.Font("Times New Roman", 1, 18));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel2.setText("Total c/ Desconto");

        gravaItensOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ìconIncluir.png"))); // NOI18N
        gravaItensOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravaItensOSActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adicionaItem)
                            .addComponent(removeItem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDesconto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gravaItensOS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(143, 143, 143)
                            .addComponent(adicionaItem)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(removeItem))
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gravaItensOS)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.getAccessibleContext().setAccessibleName("Serviços Aplicados a OS");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarTelaServicoContrato(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_carregarTelaServicoContrato
        try {
            this.salvarItensOriginais(tabelaServicosOS);
            this.txtTotal.setText(txtTotalTelaOS.getText());
            this.servicoAction.popularListaServicos(tableServicosDisponiveis);
            this.ordemServicoAction.popularServicosPedido(tabelaServicosOSGerenciador);
        } catch (Exception ex) {
            Logger.getLogger(FrmGerenciaServicosOS.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }//GEN-LAST:event_carregarTelaServicoContrato


    /*Metodo Responsavel por adicionar itens de serviço
     ao contrato e atualizar os valores nos campos e tabelas*/
    private void adicionaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionaItemActionPerformed

            int linhaSelecionada = tableServicosDisponiveis.getSelectedRow();
            List itensOS = ((ServicoPedidoTableModel)tabelaServicosOSGerenciador.getModel()).getLinhas();
            Object itemEscolhido = ((ServicoDisponivelTableModel)tableServicosDisponiveis.getModel()).getLinhas().get(linhaSelecionada);
            ItemPedido i = this.getOrdemServicoAction().converterServicoToItemPedido((Servico) itemEscolhido);

            if(this.getOrdemServicoAction().isItemEscolhido(itensOS, i)){
                javax.swing.JOptionPane.showMessageDialog(this, "Não é possivel adicionar um serviço já contratado!","Aviso",1);
            }else{                                
                i = this.atualizarValorTotal(i);
                ((ServicoPedidoTableModel)tabelaServicosOSGerenciador.getModel()).addItem(i);
            }
    }//GEN-LAST:event_adicionaItemActionPerformed


    private ItemPedido atualizarValorTotal(ItemPedido i){

        int desconto = Integer.parseInt(txtDesconto.getText());
        Double valorCalculo = 0.0 ;
        try {
            Double valorTotal = new Util().converteValorTextoDouble(txtTotal.getText());

            if(desconto <0){
                desconto = 0;
                txtDesconto.setText("0");
                valorCalculo = i.getValor();
                valorTotal = valorTotal + valorCalculo;
            }

            if(desconto>0){
                valorCalculo = i.getValor() - ((i.getValor() * desconto)/100);
                valorTotal = valorTotal + valorCalculo;
                i.setValor(valorCalculo);
            }
            txtTotal.setText(new Util().formataMoeda(valorTotal));
        } catch (ParseException ex) {
            Logger.getLogger(FrmGerenciaServicosOS.class.getName()).log(Level.SEVERE, null, ex);
        }
        return i;
    }

    private void validaDesconto(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_validaDesconto

    }//GEN-LAST:event_validaDesconto

    private void removeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemActionPerformed

        int linhaSelecionada = tabelaServicosOSGerenciador.getSelectedRow();
        Object itemEscolhido = ((ServicoPedidoTableModel)tabelaServicosOSGerenciador.getModel()).getLinhas().get(linhaSelecionada);

        if(this.getOrdemServicoAction().isItemOriginal(itensOriginais, (ItemPedido)itemEscolhido)){
             javax.swing.JOptionPane.showMessageDialog(this, "Não é possivel remover um serviço listado pelo contrato!","Aviso",1);
        }else{
            this.subtrairValorServico(((ItemPedido)itemEscolhido).getValor());
            ((ServicoPedidoTableModel)tabelaServicosOSGerenciador.getModel()).removeItemPedido(linhaSelecionada);
        }
    }//GEN-LAST:event_removeItemActionPerformed

    public void subtrairValorServico(Double valor){
        try {
            Double valorTotal = new Util().converteValorTextoDouble(txtTotal.getText());
            valorTotal = valorTotal - valor;
            txtTotal.setText(new Util().formataMoeda(valorTotal));
        } catch (ParseException ex) {
            Logger.getLogger(FrmGerenciaServicosOS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void gravaItensOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravaItensOSActionPerformed
        try {
            this.frmPrincipal.atualizarTotalOS(new Util().converteValorTextoDouble(txtTotal.getText()));
            //this.getOrdemServicoAction().setItensContratados(((ServicoPedidoTableModel)tabelaServicosOSGerenciador.getModel()).getLinhas());
        } catch (ParseException ex) {
            Logger.getLogger(FrmGerenciaServicosOS.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_gravaItensOSActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        txtTotal.setText(new Util().formataMoeda(valorTotalOriginal));
        ((ServicoPedidoTableModel)tabelaServicosOSGerenciador.getModel()).limpar();
        ((ServicoPedidoTableModel)tabelaServicosOSGerenciador.getModel()).addListaDeItens(itensOriginais);
    }//GEN-LAST:event_cancelarActionPerformed

    private void fecharJanela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fecharJanela

        txtTotal.setText(new Util().formataMoeda(valorTotalOriginal));
        ((ServicoPedidoTableModel)tabelaServicosOSGerenciador.getModel()).limpar();
        ((ServicoPedidoTableModel)tabelaServicosOSGerenciador.getModel()).addListaDeItens(itensOriginais);
     
    }//GEN-LAST:event_fecharJanela

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGerenciaServicosOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionaItem;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton gravaItensOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeItem;
    private javax.swing.JTable tabelaServicosOSGerenciador;
    private javax.swing.JTable tableServicosDisponiveis;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

 



    /**
     * @return the ordemServicoAction
     */
    public OrdemServicoAction getOrdemServicoAction() {
        return ordemServicoAction;
    }

    /**
     * @param ordemServicoAction the ordemServicoAction to set
     */
    public void setOrdemServicoAction(OrdemServicoAction ordemServicoAction) {
        this.ordemServicoAction = ordemServicoAction;
    }

    /**
     * @return the servicoAction
     */
    public ServicoAction getServicoAction() {
        return servicoAction;
    }

    /**
     * @param servicoAction the servicoAction to set
     */
    public void setServicoAction(ServicoAction servicoAction) {
        this.servicoAction = servicoAction;
    }



}
