/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewBeanForm.java
 *
 * Created on 27/05/2012, 11:09:55
 */

package br.com.syscontrol.formularios;

/**
 *
 * @author Diego
 */
public class NewBeanForm extends br.com.syscontrol.controller.PedidoAction {

    /** Creates new form NewBeanForm */
    public NewBeanForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

    }
    // </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
